apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cijug
  name: github-actions

---
apiVersion: v1
kind: Secret
metadata:
  namespace: cijug
  name: github-actions-secret
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cijug
  name: deployment-role
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-role-github-actions
  namespace: cijug
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: cijug
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: ""
