apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cijug
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: "app-image"
    newName: "ghcr.io/andreaschristianson/pipeline-to-ingress:latest"
    newTag: "initial"