name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

env:
  MAVEN_ARGS: -ntp

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: test
        run: >
          mvn clean verify
