name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

env:
  MAVEN_ARGS: -ntp

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: test
        run: >
          mvn clean verify

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  Deploy-k8s:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.12'
        name: install kubectl
      - name: setup kubectl config
        run: |
          mkdir ${HOME}/.kube
          echo "${{secrets.KUBE_CONFIG}}" >> ${HOME}/.kube/config
        shell: bash
      - name: confirm kubectl config
        run: |
          kubectl version
